# Generated by Django 3.2.9 on 2026-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='frozen_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='冻结原因'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='frozen_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='冻结时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='账户是否冻结'),
        ),
    ]
