# Generated by Django 3.2.9 on 2026-05-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='装备名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='equipment_img/', verbose_name='装备图片')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='装备简介')),
                ('is_shelf', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '露营装备',
                'verbose_name_plural': '露营装备',
            },
        ),
    ]
