# Generated by Django 3.2.9 on 2026-06-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20260525_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='daily_rental',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='日租金'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='押金'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_sold_out',
            field=models.BooleanField(default=False, verbose_name='是否售出'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments_category', to='equipment.category', verbose_name='所属分类'),
        ),
    ]
