# Generated by Django 3.2.9 on 2026-07-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_category_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('category', 'name')},
        ),
    ]
