# Generated by Django 3.2.9 on 2026-05-25 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=64, verbose_name='订单编号')),
                ('order_status', models.IntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已完成'), (4, '已取消')], default=1, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价')),
                ('start_time', models.DateTimeField(verbose_name='租赁开始时间')),
                ('end_time', models.DateTimeField(verbose_name='租赁结束时间')),
                ('contact_name', models.CharField(max_length=20, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='租赁单价')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='租赁数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单品小计')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='equipment.equipment', verbose_name='租赁装备')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='所属订单')),
            ],
        ),
    ]
