# Generated by Django 3.2.9 on 2026-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='退款金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_apply_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款申请时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_fail_reason',
            field=models.TextField(blank=True, null=True, verbose_name='退款失败原因'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_fail_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款失败时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason_custom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义退款原因'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason_type',
            field=models.CharField(blank=True, choices=[('change_mind', '不想租了'), ('schedule_conflict', '时间冲突'), ('equipment_issue', '装备问题'), ('price_concern', '价格问题'), ('other', '其他')], max_length=50, null=True, verbose_name='退款原因类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.IntegerField(choices=[(0, '未退款'), (1, '退款中'), (2, '退款成功'), (3, '退款失败')], default=0, verbose_name='退款状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_success_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款成功时间'),
        ),
    ]
