# Generated by Django 3.2.9 on 2026-06-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20260618_2223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20260602_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '订单项', 'verbose_name_plural': '订单项'},
        ),
        migrations.AddField(
            model_name='order',
            name='actual_return_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际退还金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='买断金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已冻结'), (2, '已退还'), (3, '扣除')], default=0, verbose_name='押金状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_buyout',
            field=models.BooleanField(default=False, verbose_name='是否买断'),
        ),
        migrations.AddField(
            model_name='order',
            name='overdue_days',
            field=models.IntegerField(default=0, verbose_name='逾期天数'),
        ),
        migrations.AddField(
            model_name='order',
            name='overdue_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='逾期费'),
        ),
        migrations.AddField(
            model_name='order',
            name='overdue_rate',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=5, verbose_name='逾期费比例(%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='租金'),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_days',
            field=models.IntegerField(default=0, verbose_name='租赁天数'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rental_days',
            field=models.IntegerField(default=1, verbose_name='租赁天数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已支付'), (4, '已取消'), (5, '已买断')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='订单总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='equipment.equipment', verbose_name='租赁装备'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='日租金单价'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单品小计'),
        ),
    ]
