# Generated by Django 3.2.9 on 2026-06-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20260618_2223'),
        ('orders', '0004_auto_20260618_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='overdue_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='逾期欠费'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem_equipment', to='equipment.equipment', verbose_name='租赁装备'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='租赁单价'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rental_days',
            field=models.IntegerField(verbose_name='租赁天数'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单品小计'),
        ),
    ]
