# Generated by Django 3.2.9 on 2026-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已支付待发货'), (3, '租赁中'), (4, '待归还'), (5, '已归还'), (6, '已取消'), (7, '已买断')], default=1, verbose_name='订单状态'),
        ),
    ]
